title: Presentations - Saskia Hiltemann
email: saskiahiltemann@gmail.com
description: >
  Slides and posters from various presentations
repository: "shiltemann/slides"
twitter: shiltemann
linkedin: saskiahiltemann
gitter: shiltemann
orcid: 0000-0003-3803-468X
url: "https://shiltemann.github.io"
baseurl: "/slides"
